{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "kotlin-service",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-service-1.0.1.jar",
          "url": "kotlin-service-1.0.1.jar",
          "size": 17376,
          "sha512": "5ba753a90137ffdbdad27d674ce8c45192f6658612e925c33df53af83f537bc38ae17a7a4f84788ac336a861c036b9e271cde654842f7d51db65fea7cca21447",
          "sha256": "1bba8303cd4ec25bcbbf2b572c8a660534671675a89ac1f2bca01eec458d9003",
          "sha1": "f9264dc23255715ce0946c4694e44eb042619030",
          "md5": "8f51c6f89feed7071e6050c6cf1764cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "docker",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-service-1.0.1.jar",
          "url": "kotlin-service-1.0.1.jar",
          "size": 17376,
          "sha512": "5ba753a90137ffdbdad27d674ce8c45192f6658612e925c33df53af83f537bc38ae17a7a4f84788ac336a861c036b9e271cde654842f7d51db65fea7cca21447",
          "sha256": "1bba8303cd4ec25bcbbf2b572c8a660534671675a89ac1f2bca01eec458d9003",
          "sha1": "f9264dc23255715ce0946c4694e44eb042619030",
          "md5": "8f51c6f89feed7071e6050c6cf1764cb"
        }
      ]
    }
  ]
}
