{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.7.0/multiplatform-utils-0.7.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.7.0.jar",
          "url": "multiplatform-utils-jvm-0.7.0.jar",
          "size": 23948,
          "sha512": "ae508f93d7d298bdead9eb7a8980f34c21a153644754c907e1e9d8fab1bd26b08e0338d0188febe27cc75b629e6ba6859cbff98bea6016d0e233330ff4e131b5",
          "sha256": "3839bbe64ef549886230c77debc03cc189147de3ed2f9f145fb3517f126c1a2e",
          "sha1": "ebb6234052a1d9d6c9ba3302016c97156620ec3b",
          "md5": "78a8a5446b6e4527ea1a03090d5c48c4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.7.0.jar",
          "url": "multiplatform-utils-jvm-0.7.0.jar",
          "size": 23948,
          "sha512": "ae508f93d7d298bdead9eb7a8980f34c21a153644754c907e1e9d8fab1bd26b08e0338d0188febe27cc75b629e6ba6859cbff98bea6016d0e233330ff4e131b5",
          "sha256": "3839bbe64ef549886230c77debc03cc189147de3ed2f9f145fb3517f126c1a2e",
          "sha1": "ebb6234052a1d9d6c9ba3302016c97156620ec3b",
          "md5": "78a8a5446b6e4527ea1a03090d5c48c4"
        }
      ]
    }
  ]
}
