{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.6.3/multiplatform-utils-ktor-0.6.3.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.6.3.jar",
          "url": "multiplatform-utils-ktor-jvm-0.6.3.jar",
          "size": 47335,
          "sha512": "70426ed6d16d9ef26c29ac18c448449ff6f8b27c3752baa02747353bbb086b3956255d8534979022f54dd792d2804f155e3d7b2766cbc7e083370519ac93958a",
          "sha256": "a91414b5430845161d4227b9825ec16818e6a7972fd75ab234101db91294775c",
          "sha1": "25fc2378672f5596b6f35ce321cb00e5d0294945",
          "md5": "f1ed8c7ad5123f388925d86026fc6d6d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.6.3.jar",
          "url": "multiplatform-utils-ktor-jvm-0.6.3.jar",
          "size": 47335,
          "sha512": "70426ed6d16d9ef26c29ac18c448449ff6f8b27c3752baa02747353bbb086b3956255d8534979022f54dd792d2804f155e3d7b2766cbc7e083370519ac93958a",
          "sha256": "a91414b5430845161d4227b9825ec16818e6a7972fd75ab234101db91294775c",
          "sha1": "25fc2378672f5596b6f35ce321cb00e5d0294945",
          "md5": "f1ed8c7ad5123f388925d86026fc6d6d"
        }
      ]
    }
  ]
}
