{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner",
    "module": "kotlin",
    "version": "0.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-0.3.5.jar",
          "url": "kotlin-0.3.5.jar",
          "size": 23895,
          "sha512": "dfb3a3e0041a39dcad13c0585ffd99643d4e8b4960ac28ee84622728d45cdc04c14013d81538458d292391083dd70e979969d1b52e1686f489b7571393e00034",
          "sha256": "2b85556484a921b0f6ca6892ad8f14f251cd20e23b92e854832fcc8b176a8b7b",
          "sha1": "724fd3945aa5039379226d45972de9bafbd215b4",
          "md5": "cea8356a4777f8762e1843236b917f4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-0.3.5.jar",
          "url": "kotlin-0.3.5.jar",
          "size": 23895,
          "sha512": "dfb3a3e0041a39dcad13c0585ffd99643d4e8b4960ac28ee84622728d45cdc04c14013d81538458d292391083dd70e979969d1b52e1686f489b7571393e00034",
          "sha256": "2b85556484a921b0f6ca6892ad8f14f251cd20e23b92e854832fcc8b176a8b7b",
          "sha1": "724fd3945aa5039379226d45972de9bafbd215b4",
          "md5": "cea8356a4777f8762e1843236b917f4f"
        }
      ]
    }
  ]
}
