{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0.kui",
    "module": "kui-test",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "s66ryuz5mrdthjkylirab2nncy"
    }
  },
  "variants": [
    {
      "name": "Js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kui-test-0.10.0.jar",
          "url": "kui-test-0.10.0.jar",
          "size": 41248,
          "sha512": "7d8d39836842f8335180d0442674aa7e242fbac13f7a8847c5a2ec1f858a6e9409376f0cc24aa493ebb4a0088608b72790b1e46fcc9fcdc740d7447cec2ca6d2",
          "sha256": "7e1bb65fcc8d0fe9d81208138087b09f3c58b8d401f430c2b1a83348b7a3d6cc",
          "sha1": "756bed6adc38e33a4226f0c685293408db65990c",
          "md5": "1e24e656393b6be21d99a275126a7ead"
        }
      ]
    },
    {
      "name": "Js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.juggernaut0.kui",
          "module": "kui",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "kui-test-0.10.0.jar",
          "url": "kui-test-0.10.0.jar",
          "size": 41248,
          "sha512": "7d8d39836842f8335180d0442674aa7e242fbac13f7a8847c5a2ec1f858a6e9409376f0cc24aa493ebb4a0088608b72790b1e46fcc9fcdc740d7447cec2ca6d2",
          "sha256": "7e1bb65fcc8d0fe9d81208138087b09f3c58b8d401f430c2b1a83348b7a3d6cc",
          "sha1": "756bed6adc38e33a4226f0c685293408db65990c",
          "md5": "1e24e656393b6be21d99a275126a7ead"
        }
      ]
    }
  ]
}
