{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "common-utils",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "common-utils-1.0.3.jar",
          "url": "common-utils-1.0.3.jar",
          "size": 5501,
          "sha512": "8a8c82f777e0b69e507c3c5d639dfe57a0ac1a81f85432e199cf69c1b65480492404eef2755a174fabf49eef7ec7f9cd0200e00252535933f0d6f23c2d655df3",
          "sha256": "caf81cc5fa0e449c2ce43be57ea6ecec241290421163cf2b307c031c98b6a6c7",
          "sha1": "c29079e427affb2d6fb219797a6a9ba59b6921cb",
          "md5": "2f2e94370dc964599829c1ba198473ba"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "common-utils-1.0.3.jar",
          "url": "common-utils-1.0.3.jar",
          "size": 5501,
          "sha512": "8a8c82f777e0b69e507c3c5d639dfe57a0ac1a81f85432e199cf69c1b65480492404eef2755a174fabf49eef7ec7f9cd0200e00252535933f0d6f23c2d655df3",
          "sha256": "caf81cc5fa0e449c2ce43be57ea6ecec241290421163cf2b307c031c98b6a6c7",
          "sha1": "c29079e427affb2d6fb219797a6a9ba59b6921cb",
          "md5": "2f2e94370dc964599829c1ba198473ba"
        }
      ]
    }
  ]
}
