{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-javalin",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.javalin",
          "module": "javalin",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-javalin-0.9.0.jar",
          "url": "multiplatform-utils-javalin-0.9.0.jar",
          "size": 22077,
          "sha512": "42b2296b88ac9a2d22073a64df789ca5485aadbc87f715cd3291ef0a635a5ae927dafcba970322f6829aadd017e9b052697029e87c9492db451fa14bbb48572c",
          "sha256": "d44fbdb32da8588acdff900f6616c0cc15b7d849f3f0a4fedc0732e3e8f2c1dc",
          "sha1": "724a5a949402e634e56e6d3b165c2e7a755f8ece",
          "md5": "36401aa47f3e19dcf8f96b55dbc74128"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.javalin",
          "module": "javalin",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-javalin-0.9.0.jar",
          "url": "multiplatform-utils-javalin-0.9.0.jar",
          "size": 22077,
          "sha512": "42b2296b88ac9a2d22073a64df789ca5485aadbc87f715cd3291ef0a635a5ae927dafcba970322f6829aadd017e9b052697029e87c9492db451fa14bbb48572c",
          "sha256": "d44fbdb32da8588acdff900f6616c0cc15b7d849f3f0a4fedc0732e3e8f2c1dc",
          "sha1": "724a5a949402e634e56e6d3b165c2e7a755f8ece",
          "md5": "36401aa47f3e19dcf8f96b55dbc74128"
        }
      ]
    }
  ]
}
