{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0.kui",
    "module": "kui",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "s66ryuz5mrdthjkylirab2nncy"
    }
  },
  "variants": [
    {
      "name": "Js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kui-0.10.0.jar",
          "url": "kui-0.10.0.jar",
          "size": 46728,
          "sha512": "619e1ba8d32392fd1f914c1e996ba550622043ce355c59f97c76beabef70dda813aacf66b40fa47d142625df46029e387cb17b9c2909dc380e9a9a2baa15fb8d",
          "sha256": "562adf6a5111975fb989df1b13d923533b4e22a719d6dbeead7cbbcef72ba2cf",
          "sha1": "3ce098c143fc00f1899ea64be349c8230712b014",
          "md5": "658e3031a1533b889fed1179f274f302"
        }
      ]
    },
    {
      "name": "Js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "kui-0.10.0.jar",
          "url": "kui-0.10.0.jar",
          "size": 46728,
          "sha512": "619e1ba8d32392fd1f914c1e996ba550622043ce355c59f97c76beabef70dda813aacf66b40fa47d142625df46029e387cb17b9c2909dc380e9a9a2baa15fb8d",
          "sha256": "562adf6a5111975fb989df1b13d923533b4e22a719d6dbeead7cbbcef72ba2cf",
          "sha1": "3ce098c143fc00f1899ea64be349c8230712b014",
          "md5": "658e3031a1533b889fed1179f274f302"
        }
      ]
    }
  ]
}
