{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.5.0/multiplatform-utils-ktor-0.5.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "apscvob7s5eqjohwp24x5vkgwm"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-js-0.5.0.jar",
          "url": "multiplatform-utils-ktor-js-0.5.0.jar",
          "size": 28810,
          "sha512": "92e4829e3171a594f109da0632108a3efde30c033fb9a38010d3aed9272c639183b23d69b16be672d19d7b8a872fb922ee230ef9dba10cead28b506136a51301",
          "sha256": "e47c8e4a0f6cff5010e23724b4b29815764e026ff64100a287e2dde1c53e4a8f",
          "sha1": "f149a0d59ddd98575615190b128b2abef366c39a",
          "md5": "ce5105536fc0cab3ff57116bc6fc5a53"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-js-0.5.0.jar",
          "url": "multiplatform-utils-ktor-js-0.5.0.jar",
          "size": 28810,
          "sha512": "92e4829e3171a594f109da0632108a3efde30c033fb9a38010d3aed9272c639183b23d69b16be672d19d7b8a872fb922ee230ef9dba10cead28b506136a51301",
          "sha256": "e47c8e4a0f6cff5010e23724b4b29815764e026ff64100a287e2dde1c53e4a8f",
          "sha1": "f149a0d59ddd98575615190b128b2abef366c39a",
          "md5": "ce5105536fc0cab3ff57116bc6fc5a53"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-metadata/0.5.0/multiplatform-utils-ktor-metadata-0.5.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-metadata",
        "version": "0.5.0"
      }
    }
  ]
}
