{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner",
    "module": "gradle-plugins",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-plugins-0.3.0.jar",
          "url": "gradle-plugins-0.3.0.jar",
          "size": 43339,
          "sha512": "f443096ba9d655b8854cb697d37af1402e031691bec33e85afbf2eedb24e050353b29e5c38b3ff3fc2b0a46984532a0dcf3a98ba7d6f1ab2deca6ee3dc369730",
          "sha256": "64739771a52d4e8cad376979fd765c318c4d951feb7271eddba623c0062c670f",
          "sha1": "4f9ccc0343afa2db51696bed19b6b486b5a057b5",
          "md5": "50b8779cf9badea3d51f3ed802417eca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.bmuschko.docker-remote-api",
          "module": "com.bmuschko.docker-remote-api.gradle.plugin",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugins-0.3.0.jar",
          "url": "gradle-plugins-0.3.0.jar",
          "size": 43339,
          "sha512": "f443096ba9d655b8854cb697d37af1402e031691bec33e85afbf2eedb24e050353b29e5c38b3ff3fc2b0a46984532a0dcf3a98ba7d6f1ab2deca6ee3dc369730",
          "sha256": "64739771a52d4e8cad376979fd765c318c4d951feb7271eddba623c0062c670f",
          "sha1": "4f9ccc0343afa2db51696bed19b6b486b5a057b5",
          "md5": "50b8779cf9badea3d51f3ed802417eca"
        }
      ]
    }
  ]
}
