{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner",
    "module": "gradle-plugins",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-plugins-0.3.0.jar",
          "url": "gradle-plugins-0.3.0.jar",
          "size": 43339,
          "sha512": "fdb8c50227262e393e979cbe74ec29573849efe511ba65279b58badabcf944b027e20776e04a7d4a64ed28d75b9b9afdf3df7e57f09a0a458ee636ec37b93549",
          "sha256": "e178c51d90e854749552502ebf3f8ab7fb96c4679c0747281415e46b2a455837",
          "sha1": "f853c3caf20bf7d1c75886a92259eb2ba7a1d81e",
          "md5": "f1d2dd284b3b327355fa5979c8458768"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "com.bmuschko.docker-remote-api",
          "module": "com.bmuschko.docker-remote-api.gradle.plugin",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugins-0.3.0.jar",
          "url": "gradle-plugins-0.3.0.jar",
          "size": 43339,
          "sha512": "fdb8c50227262e393e979cbe74ec29573849efe511ba65279b58badabcf944b027e20776e04a7d4a64ed28d75b9b9afdf3df7e57f09a0a458ee636ec37b93549",
          "sha256": "e178c51d90e854749552502ebf3f8ab7fb96c4679c0747281415e46b2a455837",
          "sha1": "f853c3caf20bf7d1c75886a92259eb2ba7a1d81e",
          "md5": "f1d2dd284b3b327355fa5979c8458768"
        }
      ]
    }
  ]
}
