{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.3.0/multiplatform-utils-0.3.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "lwswpclfprbxxf4twq2eiffsrq"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.3.0.jar",
          "url": "multiplatform-utils-jvm-0.3.0.jar",
          "size": 21837,
          "sha512": "6cbb6da20faabf013c2cbc46fd7312179368ed0045206310cfcd2733394c5ad8a3a3e4ae6ec3628b941bb5e9679a2845fafdab9c01b8a1b6564d69539a9df0e7",
          "sha256": "3fa18512747678e73d40165a0436feb895cc9e1dcfabbeeaa29641ed0ac128e1",
          "sha1": "9c318fcf76ba75b23943ae885c657e2346ae6454",
          "md5": "817d33e091b7ce4c460848077bfcdf7c"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.3.0.jar",
          "url": "multiplatform-utils-jvm-0.3.0.jar",
          "size": 21837,
          "sha512": "6cbb6da20faabf013c2cbc46fd7312179368ed0045206310cfcd2733394c5ad8a3a3e4ae6ec3628b941bb5e9679a2845fafdab9c01b8a1b6564d69539a9df0e7",
          "sha256": "3fa18512747678e73d40165a0436feb895cc9e1dcfabbeeaa29641ed0ac128e1",
          "sha1": "9c318fcf76ba75b23943ae885c657e2346ae6454",
          "md5": "817d33e091b7ce4c460848077bfcdf7c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-metadata/0.3.0/multiplatform-utils-metadata-0.3.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-metadata",
        "version": "0.3.0"
      }
    }
  ]
}
