{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "docker",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "docker-1.0.3.jar",
          "url": "docker-1.0.3.jar",
          "size": 9174,
          "sha512": "866f0bd65303379b4df662e3c65f726c7bc51df847e3ae91d9eb4ba7ac4437b3ef5af7996cc82c78b7d25c6e9a6f85957687c307e29692fc6629622e6c4f96c2",
          "sha256": "3046ac20bb8d90f175847b97f7da02373f6bd8daf84c5fc02db78f294690a2ac",
          "sha1": "d2b775ad36c55d9274aab81fb4c7492092dca377",
          "md5": "86ca619919e68089f6ea342fa0b623d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.cloud.tools",
          "module": "jib-gradle-plugin",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "docker-1.0.3.jar",
          "url": "docker-1.0.3.jar",
          "size": 9174,
          "sha512": "866f0bd65303379b4df662e3c65f726c7bc51df847e3ae91d9eb4ba7ac4437b3ef5af7996cc82c78b7d25c6e9a6f85957687c307e29692fc6629622e6c4f96c2",
          "sha256": "3046ac20bb8d90f175847b97f7da02373f6bd8daf84c5fc02db78f294690a2ac",
          "sha1": "d2b775ad36c55d9274aab81fb4c7492092dca377",
          "md5": "86ca619919e68089f6ea342fa0b623d1"
        }
      ]
    }
  ]
}
