{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "kotlin-service",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-service-1.0.0.jar",
          "url": "kotlin-service-1.0.0.jar",
          "size": 17376,
          "sha512": "0c7577c79178e96b331e764db553fd061e27356d4c39106818cd8d2104acbd3d5000e04f877bff54185c1db679dbedf8e5ef315e8e665275e4f64e482016b044",
          "sha256": "b9f68ce2dfefa03db622fe6d991080b4c8b7bc80e4b785cbac88d4d853ff85c7",
          "sha1": "0ba12dd8dca821023892905f3dd44669ccda51c6",
          "md5": "0529296af6abf0a742398cd024238d83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "docker",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-service-1.0.0.jar",
          "url": "kotlin-service-1.0.0.jar",
          "size": 17376,
          "sha512": "0c7577c79178e96b331e764db553fd061e27356d4c39106818cd8d2104acbd3d5000e04f877bff54185c1db679dbedf8e5ef315e8e665275e4f64e482016b044",
          "sha256": "b9f68ce2dfefa03db622fe6d991080b4c8b7bc80e4b785cbac88d4d853ff85c7",
          "sha1": "0ba12dd8dca821023892905f3dd44669ccda51c6",
          "md5": "0529296af6abf0a742398cd024238d83"
        }
      ]
    }
  ]
}
