{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.3.0/multiplatform-utils-ktor-0.3.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "lwswpclfprbxxf4twq2eiffsrq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-js-0.3.0.jar",
          "url": "multiplatform-utils-ktor-js-0.3.0.jar",
          "size": 9870,
          "sha512": "e88532d619400f7c7065ae34633d186196b4403649bdc44359df29dbdf0865cc268b3ad31dca4040022a31107a079e5b16483d7525617da8c3bfe66310b7f326",
          "sha256": "b0af74230b328f976ec40de95170ad9a7bb15707d92e811baa1fc4846fdceee8",
          "sha1": "f81cf1112a28e1570a511407f87a551737563a74",
          "md5": "d1c675b793da577fcd2a8389a49ee5f8"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-js-0.3.0.jar",
          "url": "multiplatform-utils-ktor-js-0.3.0.jar",
          "size": 9870,
          "sha512": "e88532d619400f7c7065ae34633d186196b4403649bdc44359df29dbdf0865cc268b3ad31dca4040022a31107a079e5b16483d7525617da8c3bfe66310b7f326",
          "sha256": "b0af74230b328f976ec40de95170ad9a7bb15707d92e811baa1fc4846fdceee8",
          "sha1": "f81cf1112a28e1570a511407f87a551737563a74",
          "md5": "d1c675b793da577fcd2a8389a49ee5f8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-metadata/0.3.0/multiplatform-utils-ktor-metadata-0.3.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-metadata",
        "version": "0.3.0"
      }
    }
  ]
}
