{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-metadata-0.6.1.jar",
          "url": "multiplatform-utils-ktor-0.6.1.jar",
          "size": 2865,
          "sha512": "c8fe1c9023e69cba0efdc05917b22959b888593e28e69756949a9e71030309de6620d913af0c16c12413fe02969971eaa894b0dbbbfcacb6d8084af36ea78ec7",
          "sha256": "a468a77f5b5c17d77fe9c8c34456af1e99b8d13a70f07540476b07653a32ea9a",
          "sha1": "3224d53571bb3fb440186f091241b46cbfc0df28",
          "md5": "d8570bfc0d5c2c6fb8733a9176f37848"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-js/0.6.1/multiplatform-utils-ktor-js-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-js/0.6.1/multiplatform-utils-ktor-js-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-jvm/0.6.1/multiplatform-utils-ktor-jvm-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-jvm/0.6.1/multiplatform-utils-ktor-jvm-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-jvm",
        "version": "0.6.1"
      }
    }
  ]
}
