{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "db",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "db-1.0.1.jar",
          "url": "db-1.0.1.jar",
          "size": 38382,
          "sha512": "5eafe13f30630fec5f530ad9b5a5eb109e1b7d176128c7e40a0e1284ef0b2aa9a1e65e92909f74f118f918cfe41e7c3ea1152a469148582e012a3c4e67bdfb5e",
          "sha256": "4a7812de066edf06ae2bd42a3459ecc7442dab3cbc06dab8a4d3de6a8b8621a4",
          "sha1": "be6ed8724f1748f41eadf36837ac77272b878fa3",
          "md5": "69fb698b84d9fb20443312a8fa62421c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.19.4"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java-core",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java-transport-zerodep",
          "version": {
            "requires": "3.3.5"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "db-1.0.1.jar",
          "url": "db-1.0.1.jar",
          "size": 38382,
          "sha512": "5eafe13f30630fec5f530ad9b5a5eb109e1b7d176128c7e40a0e1284ef0b2aa9a1e65e92909f74f118f918cfe41e7c3ea1152a469148582e012a3c4e67bdfb5e",
          "sha256": "4a7812de066edf06ae2bd42a3459ecc7442dab3cbc06dab8a4d3de6a8b8621a4",
          "sha1": "be6ed8724f1748f41eadf36837ac77272b878fa3",
          "md5": "69fb698b84d9fb20443312a8fa62421c"
        }
      ]
    }
  ]
}
