{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.3.0/multiplatform-utils-ktor-0.3.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "lwswpclfprbxxf4twq2eiffsrq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-metadata-0.3.0.jar",
          "url": "multiplatform-utils-ktor-metadata-0.3.0.jar",
          "size": 2150,
          "sha512": "02367b53969c9ce1c999fff8f4f9f579b31659b78b5b5173a58e16cdd603491d5b09038fd6d373bf83d4f6039da62b8ef939c0595888f2c43a142ba3556839e3",
          "sha256": "39f6bce00ae4cc7307d0e7c4b543859baf5072c0812850b380bd47ab2b1f89ec",
          "sha1": "2e6751ff7dc63058a8631187694ffc88e6fc3b56",
          "md5": "ba01341b498e45eb436180cef1c6cb8c"
        }
      ]
    }
  ]
}
