{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.6.4/multiplatform-utils-ktor-0.6.4.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.6.4.jar",
          "url": "multiplatform-utils-ktor-jvm-0.6.4.jar",
          "size": 47335,
          "sha512": "040cf63385cd9863a7cbd5bc7b2227574d9e0780b9aca81391fab7672c3fc1d34fa1238a4faff3192dbe62919f3f08701cca61d018f08e1a89e80354beab2075",
          "sha256": "b63f85ab13f25c4be2a1ea14588a20fb71f609044e8c378cbdd0427fa481527f",
          "sha1": "4f0eb89f740151eb271fc5576916e68dabd64c6d",
          "md5": "3e1dea8c986caced3561d2a5aaba991e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.6.4.jar",
          "url": "multiplatform-utils-ktor-jvm-0.6.4.jar",
          "size": 47335,
          "sha512": "040cf63385cd9863a7cbd5bc7b2227574d9e0780b9aca81391fab7672c3fc1d34fa1238a4faff3192dbe62919f3f08701cca61d018f08e1a89e80354beab2075",
          "sha256": "b63f85ab13f25c4be2a1ea14588a20fb71f609044e8c378cbdd0427fa481527f",
          "sha1": "4f0eb89f740151eb271fc5576916e68dabd64c6d",
          "md5": "3e1dea8c986caced3561d2a5aaba991e"
        }
      ]
    }
  ]
}
