{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "sass",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sass-1.0.0.jar",
          "url": "sass-1.0.0.jar",
          "size": 33507,
          "sha512": "5507a88b6d34567276e6ec8a7bb5524922ae7ab7aaed2aedb2fc405bb195ef79744fbd5096554092bbe0a06d9f8406296fcf6826d18a7e5759e968e959e9cdaf",
          "sha256": "76c8a23a60bda0f304170dec0386573e8084dc75fe1c0239b92c056ebaf99774",
          "sha1": "1444210b7eef80744b6675c12f6439af92a29b9f",
          "md5": "f676580225588dc5f12748203d75ce82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sass-1.0.0.jar",
          "url": "sass-1.0.0.jar",
          "size": 33507,
          "sha512": "5507a88b6d34567276e6ec8a7bb5524922ae7ab7aaed2aedb2fc405bb195ef79744fbd5096554092bbe0a06d9f8406296fcf6826d18a7e5759e968e959e9cdaf",
          "sha256": "76c8a23a60bda0f304170dec0386573e8084dc75fe1c0239b92c056ebaf99774",
          "sha1": "1444210b7eef80744b6675c12f6439af92a29b9f",
          "md5": "f676580225588dc5f12748203d75ce82"
        }
      ]
    }
  ]
}
