{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "sass",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sass-1.0.4.jar",
          "url": "sass-1.0.4.jar",
          "size": 34824,
          "sha512": "07c5134a9ff0be215ec723ef23d952f368a8a4da13a33a2088a91d5a96e7bf910159cded428ce6031f1b6495f51560f6a11cba14b0fb3cb65685dda0c2bb3573",
          "sha256": "22714eff1e5efea542ce1a50d6d5bca2a6ebe7e3faca7184e40f9ef1c59c3abc",
          "sha1": "ab7ae57eb42e8ba5762113de2f6e25b994e2fb38",
          "md5": "ff37b6710d0b8d86561bea10aa07baa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "sass-1.0.4.jar",
          "url": "sass-1.0.4.jar",
          "size": 34824,
          "sha512": "07c5134a9ff0be215ec723ef23d952f368a8a4da13a33a2088a91d5a96e7bf910159cded428ce6031f1b6495f51560f6a11cba14b0fb3cb65685dda0c2bb3573",
          "sha256": "22714eff1e5efea542ce1a50d6d5bca2a6ebe7e3faca7184e40f9ef1c59c3abc",
          "sha1": "ab7ae57eb42e8ba5762113de2f6e25b994e2fb38",
          "md5": "ff37b6710d0b8d86561bea10aa07baa5"
        }
      ]
    }
  ]
}
