{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "async-lite",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "scjuteenavgppjtobiztwu56gq"
    }
  },
  "variants": [
    {
      "name": "Js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "async-lite-0.1.0.jar",
          "url": "async-lite-0.1.0.jar",
          "size": 9433,
          "sha512": "6c0f960ed6555325d01f2a90cb75a255b3be6d7a4cb8e2fa5d3e784d55ab0cc21258a3bd3b8061c4e885602817231f270188fbbdd2d46c16b72d8b8a340aeffc",
          "sha256": "bb4028783bd4b0b408dd9685a50ee0b6676945f8b2d45c5a5188c7885d51d928",
          "sha1": "f899a9a06d85fd2341f820ed060d1729d30ccbce",
          "md5": "f64642701e3f50fb15a3870fa859b0f5"
        }
      ]
    },
    {
      "name": "Js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "async-lite-0.1.0.jar",
          "url": "async-lite-0.1.0.jar",
          "size": 9433,
          "sha512": "6c0f960ed6555325d01f2a90cb75a255b3be6d7a4cb8e2fa5d3e784d55ab0cc21258a3bd3b8061c4e885602817231f270188fbbdd2d46c16b72d8b8a340aeffc",
          "sha256": "bb4028783bd4b0b408dd9685a50ee0b6676945f8b2d45c5a5188c7885d51d928",
          "sha1": "f899a9a06d85fd2341f820ed060d1729d30ccbce",
          "md5": "f64642701e3f50fb15a3870fa859b0f5"
        }
      ]
    }
  ]
}
