{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.4.0/multiplatform-utils-0.4.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2ulwf3p6bngqvd7bnt6eiclp4e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.0.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-metadata-0.4.0.jar",
          "url": "multiplatform-utils-metadata-0.4.0.jar",
          "size": 5396,
          "sha512": "72a71a2ac98f427de5e60381eaf3970091f8f64a8932786f435764d6665564fd1605ae52439623724a64a82fd40ed69d8b825e8c6688a7a5d53b4535a8f83e32",
          "sha256": "7ac76275fb1c63e5534c635a59fec5f626df5ce3bda87ec51c7b5e2e1b7f9a66",
          "sha1": "7b9ab6fd8ef89e339b3cbea3a69be329a88a2aee",
          "md5": "915d905ecbad0174b2e61cd014d52458"
        }
      ]
    }
  ]
}
