{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.4.0/multiplatform-utils-ktor-0.4.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2ulwf3p6bngqvd7bnt6eiclp4e"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.4.0.jar",
          "url": "multiplatform-utils-ktor-jvm-0.4.0.jar",
          "size": 42207,
          "sha512": "2347d8009a7f256820d18d9b140f9e09ddc1fc4a0737ed9cca3f9c0c273201d0d5efd0994088e4858600fc34f836c57aaf1d74de82014a0145248aee179408a2",
          "sha256": "1ff306eb352c5d82ac970e7f8ee4095105729fbef305365911c1679addb2a6cc",
          "sha1": "ff96dcf71765d63c56b98be7dc0dfb4ad39eee8e",
          "md5": "dc89e0a5c1d3a86e826e3933c550b1b2"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.4.0.jar",
          "url": "multiplatform-utils-ktor-jvm-0.4.0.jar",
          "size": 42207,
          "sha512": "2347d8009a7f256820d18d9b140f9e09ddc1fc4a0737ed9cca3f9c0c273201d0d5efd0994088e4858600fc34f836c57aaf1d74de82014a0145248aee179408a2",
          "sha256": "1ff306eb352c5d82ac970e7f8ee4095105729fbef305365911c1679addb2a6cc",
          "sha1": "ff96dcf71765d63c56b98be7dc0dfb4ad39eee8e",
          "md5": "dc89e0a5c1d3a86e826e3933c550b1b2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-metadata/0.4.0/multiplatform-utils-ktor-metadata-0.4.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-metadata",
        "version": "0.4.0"
      }
    }
  ]
}
