{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "db",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "db-1.0.3.jar",
          "url": "db-1.0.3.jar",
          "size": 38516,
          "sha512": "dbd5a5162ac37c90e3d1ef53a39c5446b42ebab444a8680a5776ef64d3aac1f4f114f274c09329d07497b88005539bfdb3c828d9ddc245fd282d246b14360810",
          "sha256": "c8c004ccced022bfe154721748321a7cc8118a1f1f94e0ad0039916f1d54c1ac",
          "sha1": "49b438f2c836e7eeb00015c1cfda8933b5089b1e",
          "md5": "47c015f9fc5c485442d6b14710bc1a23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.19.5"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java-core",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java-transport-zerodep",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "db-1.0.3.jar",
          "url": "db-1.0.3.jar",
          "size": 38516,
          "sha512": "dbd5a5162ac37c90e3d1ef53a39c5446b42ebab444a8680a5776ef64d3aac1f4f114f274c09329d07497b88005539bfdb3c828d9ddc245fd282d246b14360810",
          "sha256": "c8c004ccced022bfe154721748321a7cc8118a1f1f94e0ad0039916f1d54c1ac",
          "sha1": "49b438f2c836e7eeb00015c1cfda8933b5089b1e",
          "md5": "47c015f9fc5c485442d6b14710bc1a23"
        }
      ]
    }
  ]
}
