{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.3.0/multiplatform-utils-0.3.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "lwswpclfprbxxf4twq2eiffsrq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-js",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties-js",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.3.0.jar",
          "url": "multiplatform-utils-js-0.3.0.jar",
          "size": 47687,
          "sha512": "5271282edf7f9f8c37502779b163a1f8a94fc8802f2960eab1ee16789a152ed752676d8cee840bcf553589dfb9bd8ea8c6ebaf784fd87eb97dc478924decb6ca",
          "sha256": "3d179ffc959bfad6b47e08649daf065175f613bd8df7dc1f82ec4dd8cc0679af",
          "sha1": "d5c66255e2592d74af5fbd03144f398297f475ba",
          "md5": "f226e9a8553531c19860753f3d5ea065"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-js",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties-js",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.3.0.jar",
          "url": "multiplatform-utils-js-0.3.0.jar",
          "size": 47687,
          "sha512": "5271282edf7f9f8c37502779b163a1f8a94fc8802f2960eab1ee16789a152ed752676d8cee840bcf553589dfb9bd8ea8c6ebaf784fd87eb97dc478924decb6ca",
          "sha256": "3d179ffc959bfad6b47e08649daf065175f613bd8df7dc1f82ec4dd8cc0679af",
          "sha1": "d5c66255e2592d74af5fbd03144f398297f475ba",
          "md5": "f226e9a8553531c19860753f3d5ea065"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-metadata/0.3.0/multiplatform-utils-metadata-0.3.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-metadata",
        "version": "0.3.0"
      }
    }
  ]
}
