{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-metadata-0.6.3.jar",
          "url": "multiplatform-utils-ktor-0.6.3.jar",
          "size": 2865,
          "sha512": "8c1a4ebbadcc24cc5d6ced9b50aa884530aacb5b953ceb87742df16d5f4cd1f1108232307825be3309d8211602d4262209a8e61afc077a0c51c66015ee2c2ec3",
          "sha256": "546b339db7c8841b3decae09afe91b14727e48220c79e92f25c6e3bc8af55f70",
          "sha1": "0285f2c1d7ed4d231d2c795b2b88c09d79b99cd7",
          "md5": "9618b69ec262654c6c141a9d196ce263"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-js/0.6.3/multiplatform-utils-ktor-js-0.6.3.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-js",
        "version": "0.6.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-js/0.6.3/multiplatform-utils-ktor-js-0.6.3.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-js",
        "version": "0.6.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-jvm/0.6.3/multiplatform-utils-ktor-jvm-0.6.3.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-jvm",
        "version": "0.6.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-jvm/0.6.3/multiplatform-utils-ktor-jvm-0.6.3.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-jvm",
        "version": "0.6.3"
      }
    }
  ]
}
