{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.auth",
    "module": "auth-plugins-ktor",
    "version": "21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils-ktor",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "dev.twarner.auth",
          "module": "auth-common",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "auth-plugins-ktor-21.jar",
          "url": "auth-plugins-ktor-21.jar",
          "size": 11839,
          "sha512": "8fcd759cf3bc9f97b5a93a9438503085dee66e919905a5bedb04460a3654985f753c0c820406d64d73d3461fa3a9365edcfadab2ec2bf6b2a0ca5843170a50f4",
          "sha256": "9862987828b9b0c94c98b427439bcd3ade4dc930738217c6a3376994e1fe6822",
          "sha1": "fc8bdbf9c92f54ddf9bd712eeae252d1ca39a97f",
          "md5": "be65d6d5852acdd364d283900dea7053"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils-ktor",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "dev.twarner.auth",
          "module": "auth-common",
          "version": {
            "requires": "21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "auth-plugins-ktor-21.jar",
          "url": "auth-plugins-ktor-21.jar",
          "size": 11839,
          "sha512": "8fcd759cf3bc9f97b5a93a9438503085dee66e919905a5bedb04460a3654985f753c0c820406d64d73d3461fa3a9365edcfadab2ec2bf6b2a0ca5843170a50f4",
          "sha256": "9862987828b9b0c94c98b427439bcd3ade4dc930738217c6a3376994e1fe6822",
          "sha1": "fc8bdbf9c92f54ddf9bd712eeae252d1ca39a97f",
          "md5": "be65d6d5852acdd364d283900dea7053"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auth-plugins-ktor-21-sources.jar",
          "url": "auth-plugins-ktor-21-sources.jar",
          "size": 1439,
          "sha512": "7a28ed956655ca687c1d6531c2cb7c98105a4e5aa2c5ed004e99676d645a0dd9fdb45d8a8323621aef528f86203425b5ab1f33e6050ceb72fb9557d325b8ecaf",
          "sha256": "d6217dc7d83d587739f8629b3ddfc39d1312740b03c593bb6ef1ce3527ec33b3",
          "sha1": "cc4303c3740076c4caaae17d83552e394683ce52",
          "md5": "0980c79981a143c78050913fb97f9599"
        }
      ]
    }
  ]
}
