{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "db",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "db-1.0.0.jar",
          "url": "db-1.0.0.jar",
          "size": 38382,
          "sha512": "4d8296b82372bd4b38865d534ed4e37199df37e4c200cd8f497c76b4ab94739dd4afb1d38bf5c71ac1e978c23972e89bad2e99cfb6f9a4011c07a338c2aad2d2",
          "sha256": "72870affa3a300cef64dd63b201e1eb463d06d77bf0b6e2fe58cb8870f552830",
          "sha1": "5011ad3afeccf6e9ed760c308a2d2748db72e15a",
          "md5": "fc05a60ae91fd2379e3b219b1b0184b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.twarner.gradle",
          "module": "common-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java-core",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.github.docker-java",
          "module": "docker-java-transport-zerodep",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "db-1.0.0.jar",
          "url": "db-1.0.0.jar",
          "size": 38382,
          "sha512": "4d8296b82372bd4b38865d534ed4e37199df37e4c200cd8f497c76b4ab94739dd4afb1d38bf5c71ac1e978c23972e89bad2e99cfb6f9a4011c07a338c2aad2d2",
          "sha256": "72870affa3a300cef64dd63b201e1eb463d06d77bf0b6e2fe58cb8870f552830",
          "sha1": "5011ad3afeccf6e9ed760c308a2d2748db72e15a",
          "md5": "fc05a60ae91fd2379e3b219b1b0184b6"
        }
      ]
    }
  ]
}
