{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-metadata-0.6.4.jar",
          "url": "multiplatform-utils-0.6.4.jar",
          "size": 6132,
          "sha512": "7261d97dd0fdb3beb7289dcc6e327f9a98dbe1f1bd9ba039c97d1c1e335c2786f842033eb74e191a80ce6592f12303687687d892db1be9c21c0ed1121e75d227",
          "sha256": "ec3602de194a2ec6c8c4192805fd2e9137a38aa7c03e465c94f029b438eb4928",
          "sha1": "93a8d9b43ae1123284faeb9ac00ec5a1b864182c",
          "md5": "2c5a0cf10a38e23928db273dd39b732b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-js/0.6.4/multiplatform-utils-js-0.6.4.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-js",
        "version": "0.6.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-js/0.6.4/multiplatform-utils-js-0.6.4.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-js",
        "version": "0.6.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-jvm/0.6.4/multiplatform-utils-jvm-0.6.4.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-jvm",
        "version": "0.6.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-jvm/0.6.4/multiplatform-utils-jvm-0.6.4.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-jvm",
        "version": "0.6.4"
      }
    }
  ]
}
