{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.auth",
    "module": "auth-common",
    "version": "24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-metadata-24.jar",
          "url": "auth-common-24.jar",
          "size": 3643,
          "sha512": "8fdeebd6392f2601e72e8b19ae5257c244e845ef8a5f04002dda17cc6342b58407ff202ad409625874342f6c3943b61432ac8c29e13523136be21ae66dfcc32e",
          "sha256": "4e2a27f24d652279fc25a1cb82a5e2e869d3af298e02995d7f9522f1a7168abb",
          "sha1": "5625a94b91d29a80549ae61ca4359847dbd6909b",
          "md5": "3da9f61509f01971ddb6d0176c6714cd"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "auth-common-kotlin-24-sources.jar",
          "url": "auth-common-24-sources.jar",
          "size": 1821,
          "sha512": "53e4781b9fd55c8a5f4ec9683744f63556f017bb188b8d84e80821e2668c1abcc11db4cd4ed73bae94149550b48c41e8120bbde16b64dfbe459facf668cfb001",
          "sha256": "5f9a2898653910ab85496857a0007f9f548214419061516898c199b04469700a",
          "sha1": "6d4b9fb49db5fc3033968bdba5ce6fd2ea72cc0d",
          "md5": "00ca8966422dc9ad41b7de4e5a59c779"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../auth-common-js/24/auth-common-js-24.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-js",
        "version": "24"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../auth-common-js/24/auth-common-js-24.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-js",
        "version": "24"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../auth-common-js/24/auth-common-js-24.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-js",
        "version": "24"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-common-jvm/24/auth-common-jvm-24.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-jvm",
        "version": "24"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-common-jvm/24/auth-common-jvm-24.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-jvm",
        "version": "24"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-common-jvm/24/auth-common-jvm-24.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-jvm",
        "version": "24"
      }
    }
  ]
}
