{
  "formatVersion": "1.1",
  "component": {
    "url": "../../auth-ui/23/auth-ui-23.module",
    "group": "dev.twarner.auth",
    "module": "auth-ui",
    "version": "23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "dev.twarner.auth",
          "module": "auth-common",
          "version": {
            "requires": "23"
          }
        },
        {
          "group": "com.github.juggernaut0.kui",
          "module": "kui",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "auth-ui-js-23.klib",
          "url": "auth-ui-js-23.klib",
          "size": 26325,
          "sha512": "a0bf2fa7ec4f2c07f17944c900e47b9a9aef1fac5f07fdaf28f175aa88e60494022029e0172bc28ec1f1b1e34bbe96e67e4370642764c12d4a6afb3420d28e40",
          "sha256": "adf52657c9371d30e2e71b15899436011ebebe25dbfbfa13f44c7c556aa5821a",
          "sha1": "5a9b16b75dbe12382278204896dbdb19b126c528",
          "md5": "bece334a90d0e8b40ea28776d37c6fcd"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "dev.twarner.auth",
          "module": "auth-common",
          "version": {
            "requires": "23"
          }
        },
        {
          "group": "com.github.juggernaut0.kui",
          "module": "kui",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-ui-js-23.klib",
          "url": "auth-ui-js-23.klib",
          "size": 26325,
          "sha512": "a0bf2fa7ec4f2c07f17944c900e47b9a9aef1fac5f07fdaf28f175aa88e60494022029e0172bc28ec1f1b1e34bbe96e67e4370642764c12d4a6afb3420d28e40",
          "sha256": "adf52657c9371d30e2e71b15899436011ebebe25dbfbfa13f44c7c556aa5821a",
          "sha1": "5a9b16b75dbe12382278204896dbdb19b126c528",
          "md5": "bece334a90d0e8b40ea28776d37c6fcd"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "auth-ui-js-23-sources.jar",
          "url": "auth-ui-js-23-sources.jar",
          "size": 3984,
          "sha512": "1e3a35c23a12de8ddec77da55402aa00fbfe6c342c471bfb09f651375457ca07403f86f70dd980727d92e973fa3458250d89f9972343c70683a633ae88f8c2ef",
          "sha256": "eb41d2ad9c885f7b0b48d07e133fc89ab315dc4f20a947491d5a0223dd6ea701",
          "sha1": "5c7da08633171f2897846206db286fc1cc51e3d9",
          "md5": "6473203a8f7d77a7cdc5bddcd6f0a423"
        }
      ]
    }
  ]
}
