{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.5.0/multiplatform-utils-ktor-0.5.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "apscvob7s5eqjohwp24x5vkgwm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.5.0.jar",
          "url": "multiplatform-utils-ktor-jvm-0.5.0.jar",
          "size": 46880,
          "sha512": "b821129c8c094f8de3f76a9f499afb669ee3e14bd54f6cbe874af770a81bcf5ee9d95f80d795b377a0866d18669a13996b6bdf3a55cbe7a6c40d76e23ff5b3d6",
          "sha256": "d36fe2f70c8327a7230d6c0cced77310ec44e924cc86aa2f6de6236d30af801d",
          "sha1": "4995b8044b9ef5d12db8fd175e7168717c242dea",
          "md5": "396dd458ad76fa06e3287af1ec99a789"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.5.0.jar",
          "url": "multiplatform-utils-ktor-jvm-0.5.0.jar",
          "size": 46880,
          "sha512": "b821129c8c094f8de3f76a9f499afb669ee3e14bd54f6cbe874af770a81bcf5ee9d95f80d795b377a0866d18669a13996b6bdf3a55cbe7a6c40d76e23ff5b3d6",
          "sha256": "d36fe2f70c8327a7230d6c0cced77310ec44e924cc86aa2f6de6236d30af801d",
          "sha1": "4995b8044b9ef5d12db8fd175e7168717c242dea",
          "md5": "396dd458ad76fa06e3287af1ec99a789"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-metadata/0.5.0/multiplatform-utils-ktor-metadata-0.5.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-metadata",
        "version": "0.5.0"
      }
    }
  ]
}
