{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0.kui",
    "module": "kui",
    "version": "0.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4k3lhy5nzrcandtldy7q6dshzm"
    }
  },
  "variants": [
    {
      "name": "Js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kui-0.10.1.jar",
          "url": "kui-0.10.1.jar",
          "size": 52809,
          "sha512": "a3f0a5681f4dd4874a3627380dc52820d4b5be28f7b0953bea2098c6a85836d981a36dbdf656a88d27c308c104bd1ffe13160c2af7166084b9828deece1b517e",
          "sha256": "87fd39a29f2d500299ce0ddb7ddf841edd3c2888ed8c4cd604e0c1dd367a33b6",
          "sha1": "6286d6a919c576fdda402210fbe1cd7c24e2ebff",
          "md5": "f95d9b49d93586279e63d6f80bec0879"
        }
      ]
    },
    {
      "name": "Js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "kui-0.10.1.jar",
          "url": "kui-0.10.1.jar",
          "size": 52809,
          "sha512": "a3f0a5681f4dd4874a3627380dc52820d4b5be28f7b0953bea2098c6a85836d981a36dbdf656a88d27c308c104bd1ffe13160c2af7166084b9828deece1b517e",
          "sha256": "87fd39a29f2d500299ce0ddb7ddf841edd3c2888ed8c4cd604e0c1dd367a33b6",
          "sha1": "6286d6a919c576fdda402210fbe1cd7c24e2ebff",
          "md5": "f95d9b49d93586279e63d6f80bec0879"
        }
      ]
    }
  ]
}
