{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.2.1/multiplatform-utils-0.2.1.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "es477343uzawdivphl4k35ooxy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-metadata-0.2.1.jar",
          "url": "multiplatform-utils-metadata-0.2.1.jar",
          "size": 5292,
          "sha512": "c175690ed74e14d9a0683569966a9c9e6f2c128df0eda76eb793f524820528d639b46720b6603675bea0f334467f3178cbabc9807fdffe0ecc2355bae03a60ca",
          "sha256": "e89c3261041ccfb2cc5df85cd8f0f083f9bb39bcd56b4d3bc8572fd3744cfc3b",
          "sha1": "ce175719eee9bfc0cb3f9f226dced9c43758eb98",
          "md5": "3cb6e9dbc13379993a245962425d1bda"
        }
      ]
    }
  ]
}
