{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0.kui",
    "module": "kui-test",
    "version": "0.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4k3lhy5nzrcandtldy7q6dshzm"
    }
  },
  "variants": [
    {
      "name": "Js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kui-test-0.10.1.jar",
          "url": "kui-test-0.10.1.jar",
          "size": 41248,
          "sha512": "caee7b5c9166cc38b13bc5decfc48f0b098bc34c9a9b87b856d1c19129b0b3a6f5d1f2de0ca6e6c8b188604ae83828aa96d0562bca932ec219e0f7e588097414",
          "sha256": "3b64320e35a4bcdfcb32f6d6b8f2bdbcbc8c31cf81eaa8ec64f8d5ec6e5c2c2d",
          "sha1": "ef659bf368cbf7c5221060f5af987464f8708a80",
          "md5": "0e6820b696a083229b111cab302d2550"
        }
      ]
    },
    {
      "name": "Js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "com.github.juggernaut0.kui",
          "module": "kui",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.3.61"
          }
        }
      ],
      "files": [
        {
          "name": "kui-test-0.10.1.jar",
          "url": "kui-test-0.10.1.jar",
          "size": 41248,
          "sha512": "caee7b5c9166cc38b13bc5decfc48f0b098bc34c9a9b87b856d1c19129b0b3a6f5d1f2de0ca6e6c8b188604ae83828aa96d0562bca932ec219e0f7e588097414",
          "sha256": "3b64320e35a4bcdfcb32f6d6b8f2bdbcbc8c31cf81eaa8ec64f8d5ec6e5c2c2d",
          "sha1": "ef659bf368cbf7c5221060f5af987464f8708a80",
          "md5": "0e6820b696a083229b111cab302d2550"
        }
      ]
    }
  ]
}
