{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.3.0/multiplatform-utils-ktor-0.3.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "lwswpclfprbxxf4twq2eiffsrq"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.3.0.jar",
          "url": "multiplatform-utils-ktor-jvm-0.3.0.jar",
          "size": 41583,
          "sha512": "437a48236b36a08801659dfd4b6b815b662d012aa4375e42d57cfa9d0e7de9293db9ffe5867165a5de89c707526bf3fca60b80aed2a98ac0aa0f416b669149cd",
          "sha256": "ef1560d058fb64452fcaac254e394333a64813a1492771032727215c633b280b",
          "sha1": "aeb8c6e12c4d0ef1a471cc7ed97ff99eaa66a0bd",
          "md5": "9d0497c4dbb3516836062716a440efac"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.3.0.jar",
          "url": "multiplatform-utils-ktor-jvm-0.3.0.jar",
          "size": 41583,
          "sha512": "437a48236b36a08801659dfd4b6b815b662d012aa4375e42d57cfa9d0e7de9293db9ffe5867165a5de89c707526bf3fca60b80aed2a98ac0aa0f416b669149cd",
          "sha256": "ef1560d058fb64452fcaac254e394333a64813a1492771032727215c633b280b",
          "sha1": "aeb8c6e12c4d0ef1a471cc7ed97ff99eaa66a0bd",
          "md5": "9d0497c4dbb3516836062716a440efac"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-metadata/0.3.0/multiplatform-utils-ktor-metadata-0.3.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-metadata",
        "version": "0.3.0"
      }
    }
  ]
}
