{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "kotlin-web",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-web-1.0.3.jar",
          "url": "kotlin-web-1.0.3.jar",
          "size": 27396,
          "sha512": "7013eff212ffc550f0fdf6cb9758499131aff26d8a2eced875382290e80411ae048a2c057bcc87f28431019f3ab4f4462b17221eaf048839d606db85b1d2e9a8",
          "sha256": "b4688fa3e915b291dd99453f1540cba739be0951c1c57e97c06251fdac890e3f",
          "sha1": "40e74b7d272f9df470f97b2a85baf470ffe15993",
          "md5": "624cc01fb427682b6925991bb0238529"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "sass",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "download-firefox",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-web-1.0.3.jar",
          "url": "kotlin-web-1.0.3.jar",
          "size": 27396,
          "sha512": "7013eff212ffc550f0fdf6cb9758499131aff26d8a2eced875382290e80411ae048a2c057bcc87f28431019f3ab4f4462b17221eaf048839d606db85b1d2e9a8",
          "sha256": "b4688fa3e915b291dd99453f1540cba739be0951c1c57e97c06251fdac890e3f",
          "sha1": "40e74b7d272f9df470f97b2a85baf470ffe15993",
          "md5": "624cc01fb427682b6925991bb0238529"
        }
      ]
    }
  ]
}
