{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-metadata-0.7.0.jar",
          "url": "multiplatform-utils-ktor-0.7.0.jar",
          "size": 4275,
          "sha512": "9588e0b691c77fe5207fb6ba266d7e4f4c7f960ab2afaa73f6dca90ea01568413bb3d3fe0d1cd40113986f118013ac3f207ccefca650b5a768c4af7e2532f4ee",
          "sha256": "6e2ad5bc001b5d159dacb0d21eef21f34243b58c13c5aa3a68664887caad363c",
          "sha1": "35e818d03f00e556325748e551c130ac55b4b043",
          "md5": "e3e93733f7c0bc1176ca567da5496256"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-js/0.7.0/multiplatform-utils-ktor-js-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-js/0.7.0/multiplatform-utils-ktor-js-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-jvm/0.7.0/multiplatform-utils-ktor-jvm-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-jvm",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-ktor-jvm/0.7.0/multiplatform-utils-ktor-jvm-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-ktor-jvm",
        "version": "0.7.0"
      }
    }
  ]
}
