{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "kotlin-web",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-web-1.0.0.jar",
          "url": "kotlin-web-1.0.0.jar",
          "size": 27396,
          "sha512": "e09b354ccf94815d80c260d9f8a25d1759d19afb1304f1ce443d090b6d4964fe4e599cae9e6ae177f5260f0073d29a2b7423292097635fe05287ce17b3cb54e4",
          "sha256": "dc44705757cc4e958e1cc32a88062bfaa174174c4175607cf51abe7f8aa721cd",
          "sha1": "9e4f732ef203c3725ac97f990e2911df58d5a650",
          "md5": "2be08d88f5ee9c165dc810e60fd6e60b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "sass",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "dev.twarner.gradle",
          "module": "download-firefox",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-web-1.0.0.jar",
          "url": "kotlin-web-1.0.0.jar",
          "size": 27396,
          "sha512": "e09b354ccf94815d80c260d9f8a25d1759d19afb1304f1ce443d090b6d4964fe4e599cae9e6ae177f5260f0073d29a2b7423292097635fe05287ce17b3cb54e4",
          "sha256": "dc44705757cc4e958e1cc32a88062bfaa174174c4175607cf51abe7f8aa721cd",
          "sha1": "9e4f732ef203c3725ac97f990e2911df58d5a650",
          "md5": "2be08d88f5ee9c165dc810e60fd6e60b"
        }
      ]
    }
  ]
}
