{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.gradle",
    "module": "download-firefox",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "download-firefox-1.0.1.jar",
          "url": "download-firefox-1.0.1.jar",
          "size": 27435,
          "sha512": "0d8565edceeda6f296bbc82660b37881b7ec8320d77784b1d6e1fcd67adeb91b1553065b1c4cf7a4ea3c5963a7bc76513e2ea0510f85c1cb42700db236a911a5",
          "sha256": "dc1834c5a88bf84a590927561cd4a08be2757847b9cd271692ca2a2b5ba07465",
          "sha1": "6da139af08a9fa5ef48c84983b30d27bfc6c4745",
          "md5": "7031c000d560b8ab4ce0793cc3a4313b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "5.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-firefox-1.0.1.jar",
          "url": "download-firefox-1.0.1.jar",
          "size": 27435,
          "sha512": "0d8565edceeda6f296bbc82660b37881b7ec8320d77784b1d6e1fcd67adeb91b1553065b1c4cf7a4ea3c5963a7bc76513e2ea0510f85c1cb42700db236a911a5",
          "sha256": "dc1834c5a88bf84a590927561cd4a08be2757847b9cd271692ca2a2b5ba07465",
          "sha1": "6da139af08a9fa5ef48c84983b30d27bfc6c4745",
          "md5": "7031c000d560b8ab4ce0793cc3a4313b"
        }
      ]
    }
  ]
}
