{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-metadata-0.6.1.jar",
          "url": "multiplatform-utils-0.6.1.jar",
          "size": 6132,
          "sha512": "ca432c527004410bd84822b314c9ab6f7e473c5b63b9eef7b5626b3efbf7fe667194920b39ce9c1a108dbdb3edd537cc0728550c3614f2087f1bf25e5466d77a",
          "sha256": "16296b74d739787935061189a1a2cdbd261683a1dee577d0216b187070debed3",
          "sha1": "b9a5d2f23b1ccc9ef83ed608bb0926be5c887da2",
          "md5": "f7b3d378ff8f012a1204d533288f5003"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-js/0.6.1/multiplatform-utils-js-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-js/0.6.1/multiplatform-utils-js-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-js",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-jvm/0.6.1/multiplatform-utils-jvm-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-jvm",
        "version": "0.6.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-jvm/0.6.1/multiplatform-utils-jvm-0.6.1.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-jvm",
        "version": "0.6.1"
      }
    }
  ]
}
