{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.twarner.auth",
    "module": "auth-common",
    "version": "23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-metadata-23.jar",
          "url": "auth-common-23.jar",
          "size": 4938,
          "sha512": "69412bf9b4382aa9920d0fa6553e824047b8ee60f1821a4305ece247ce98d8c96e85451c5be54331ce8f88a46ab62f7c3f24b356eb111ab48b7505fcc8388478",
          "sha256": "6b3aa087647a436443b70cde20450f81d5b6a21bf8a17753e530e09569d220c4",
          "sha1": "ccbf06773dc12e00b17ea0839c3ff1266765fd4e",
          "md5": "5c1da6946394b30565dbef548c82279b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "auth-common-kotlin-23-sources.jar",
          "url": "auth-common-23-sources.jar",
          "size": 1821,
          "sha512": "53e4781b9fd55c8a5f4ec9683744f63556f017bb188b8d84e80821e2668c1abcc11db4cd4ed73bae94149550b48c41e8120bbde16b64dfbe459facf668cfb001",
          "sha256": "5f9a2898653910ab85496857a0007f9f548214419061516898c199b04469700a",
          "sha1": "6d4b9fb49db5fc3033968bdba5ce6fd2ea72cc0d",
          "md5": "00ca8966422dc9ad41b7de4e5a59c779"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../auth-common-js/23/auth-common-js-23.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-js",
        "version": "23"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../auth-common-js/23/auth-common-js-23.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-js",
        "version": "23"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../auth-common-js/23/auth-common-js-23.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-js",
        "version": "23"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-common-jvm/23/auth-common-jvm-23.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-jvm",
        "version": "23"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-common-jvm/23/auth-common-jvm-23.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-jvm",
        "version": "23"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../auth-common-jvm/23/auth-common-jvm-23.module",
        "group": "dev.twarner.auth",
        "module": "auth-common-jvm",
        "version": "23"
      }
    }
  ]
}
