{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.6.2/multiplatform-utils-0.6.2.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.6.2.jar",
          "url": "multiplatform-utils-js-0.6.2.jar",
          "size": 91057,
          "sha512": "9d1264119397f90deedf31d34fdfb08b728a32781d1c689b9c4baa05459d4212579acff8ad525f9570f6f407546e6858cf64a9683d26f45d7651a59dc4ec2f72",
          "sha256": "5e7da8b370b7d938b110630b43c3a6c3563762e55be315c597d08b928079efeb",
          "sha1": "b15308a9ef45d7340744cae57cce094025563311",
          "md5": "52a0b332281dae47de151049dd6f69de"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.6.2.jar",
          "url": "multiplatform-utils-js-0.6.2.jar",
          "size": 91057,
          "sha512": "9d1264119397f90deedf31d34fdfb08b728a32781d1c689b9c4baa05459d4212579acff8ad525f9570f6f407546e6858cf64a9683d26f45d7651a59dc4ec2f72",
          "sha256": "5e7da8b370b7d938b110630b43c3a6c3563762e55be315c597d08b928079efeb",
          "sha1": "b15308a9ef45d7340744cae57cce094025563311",
          "md5": "52a0b332281dae47de151049dd6f69de"
        }
      ]
    }
  ]
}
