{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.10.0/multiplatform-utils-0.10.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.10.0.jar",
          "url": "multiplatform-utils-jvm-0.10.0.jar",
          "size": 33062,
          "sha512": "05853826c931806727364cef520453fa9b647ab6bff27eedbf84b10e05969b196a13310cabd0ca961af1332a316da1bff3519d252368057556d7bb45aa8a68e4",
          "sha256": "9585eba7991999f34f7fbd3e22c155ed384027fe4d01f6934737260814b75c0c",
          "sha1": "19cf45c094568a87fdb6c6160798adde4b7e1232",
          "md5": "09494d704678998e995f2be60dbefd85"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.10.0.jar",
          "url": "multiplatform-utils-jvm-0.10.0.jar",
          "size": 33062,
          "sha512": "05853826c931806727364cef520453fa9b647ab6bff27eedbf84b10e05969b196a13310cabd0ca961af1332a316da1bff3519d252368057556d7bb45aa8a68e4",
          "sha256": "9585eba7991999f34f7fbd3e22c155ed384027fe4d01f6934737260814b75c0c",
          "sha1": "19cf45c094568a87fdb6c6160798adde4b7e1232",
          "md5": "09494d704678998e995f2be60dbefd85"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.10.0-sources.jar",
          "url": "multiplatform-utils-jvm-0.10.0-sources.jar",
          "size": 4932,
          "sha512": "83d4efaa759170d1a1d32abda5c4cb09f7446f9e259aaf5b6abba58867fa69693a2f5844271f4d6f27932d971bbde0a0e758b385b5046e4a2a51020da07dc490",
          "sha256": "5b3f2e975093f845a735e411439e99ec70f1ba3ae02b8a33ded7654f939da4e8",
          "sha1": "2a9ca108b90f1f5fddbc8c32f3d13d58f06fc124",
          "md5": "c8028cc058f2bd127fd629201f254239"
        }
      ]
    }
  ]
}
