{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-metadata-0.7.0.jar",
          "url": "multiplatform-utils-0.7.0.jar",
          "size": 5237,
          "sha512": "04c017b424fc2f6252481c6fd89aacaa623fda7920810c983692f3da4de95c53c02435fd8c1855925e0e4cf0afd5faa6a599d7de9ced14ec0dcc6f8e3a93aa8b",
          "sha256": "be7622a09f725642e1d6425c0453e0fd016108c152abd0226fb48ed73d214f00",
          "sha1": "35734c8f7f41a81f7c5bf562511f4159dd029878",
          "md5": "27d483e5b047c4493f80253927b4ce1b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-js/0.7.0/multiplatform-utils-js-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../multiplatform-utils-js/0.7.0/multiplatform-utils-js-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-js",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-jvm/0.7.0/multiplatform-utils-jvm-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-jvm",
        "version": "0.7.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multiplatform-utils-jvm/0.7.0/multiplatform-utils-jvm-0.7.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-jvm",
        "version": "0.7.0"
      }
    }
  ]
}
