{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.4.0/multiplatform-utils-0.4.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "2ulwf3p6bngqvd7bnt6eiclp4e"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.0.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.4.0.jar",
          "url": "multiplatform-utils-js-0.4.0.jar",
          "size": 49805,
          "sha512": "8eb86df7abc03a397a834a2221093e2bc7d45134ffe7675fc268310e07400fbbe0a4d2a8796a0356407d6c66493734a0dc5079ceecc31dfcb20b1e566f385089",
          "sha256": "c4e5edf08b9c6affd4d3f1c37f004c096e8bffb625a800e06f9d34340fbf07d4",
          "sha1": "634260ccde47a5107585c23c768c1c537ae81381",
          "md5": "a314850b40ba6cbe53e30c37c45868bd"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.0.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.4.0.jar",
          "url": "multiplatform-utils-js-0.4.0.jar",
          "size": 49805,
          "sha512": "8eb86df7abc03a397a834a2221093e2bc7d45134ffe7675fc268310e07400fbbe0a4d2a8796a0356407d6c66493734a0dc5079ceecc31dfcb20b1e566f385089",
          "sha256": "c4e5edf08b9c6affd4d3f1c37f004c096e8bffb625a800e06f9d34340fbf07d4",
          "sha1": "634260ccde47a5107585c23c768c1c537ae81381",
          "md5": "a314850b40ba6cbe53e30c37c45868bd"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-metadata/0.4.0/multiplatform-utils-metadata-0.4.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-metadata",
        "version": "0.4.0"
      }
    }
  ]
}
