{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.5.0/multiplatform-utils-0.5.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId": "apscvob7s5eqjohwp24x5vkgwm"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.5.0.jar",
          "url": "multiplatform-utils-js-0.5.0.jar",
          "size": 89251,
          "sha512": "5ad2077f41214dc357e72f91b94fe26a6c6adb39474b3ce79f762a4ed383068c0603af0ea1646bf2bf322a048c31a59f3d13705557c42e69aaefa38aa32ebf55",
          "sha256": "e67077af0ed04ab6cb2892e9ecd77bafd37acc07b2e5f21ce6f73d2d4cc70328",
          "sha1": "5b59f788b08a64c3c1085e76de42b7a7ff735558",
          "md5": "8a08c94de4b1282a3fcc0b963f1b9993"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "com.github.juggernaut0",
          "module": "async-lite",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-properties",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-js-0.5.0.jar",
          "url": "multiplatform-utils-js-0.5.0.jar",
          "size": 89251,
          "sha512": "5ad2077f41214dc357e72f91b94fe26a6c6adb39474b3ce79f762a4ed383068c0603af0ea1646bf2bf322a048c31a59f3d13705557c42e69aaefa38aa32ebf55",
          "sha256": "e67077af0ed04ab6cb2892e9ecd77bafd37acc07b2e5f21ce6f73d2d4cc70328",
          "sha1": "5b59f788b08a64c3c1085e76de42b7a7ff735558",
          "md5": "8a08c94de4b1282a3fcc0b963f1b9993"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-metadata/0.5.0/multiplatform-utils-metadata-0.5.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-metadata",
        "version": "0.5.0"
      }
    }
  ]
}
