{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils-ktor/0.6.2/multiplatform-utils-ktor-0.6.2.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils-ktor",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.6.2.jar",
          "url": "multiplatform-utils-ktor-jvm-0.6.2.jar",
          "size": 47457,
          "sha512": "13af58372119045e6efdbc3faf957afcfe30d1daefd902d1419c85bb0b272fc6a7805c66d98f682e8b6f26b006352024f6bcbea3e98acc48c49ab7be91c96b6d",
          "sha256": "9d6fd1f7f01f067936be399224948c76bc225d40123127a11af3078eef20ee64",
          "sha1": "4feb18793515afbb695cd2ad95035e5a9a7b2312",
          "md5": "abf9a459b516bbdab97bee897fba2f44"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-auth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "com.github.juggernaut0",
          "module": "multiplatform-utils",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-ktor-jvm-0.6.2.jar",
          "url": "multiplatform-utils-ktor-jvm-0.6.2.jar",
          "size": 47457,
          "sha512": "13af58372119045e6efdbc3faf957afcfe30d1daefd902d1419c85bb0b272fc6a7805c66d98f682e8b6f26b006352024f6bcbea3e98acc48c49ab7be91c96b6d",
          "sha256": "9d6fd1f7f01f067936be399224948c76bc225d40123127a11af3078eef20ee64",
          "sha1": "4feb18793515afbb695cd2ad95035e5a9a7b2312",
          "md5": "abf9a459b516bbdab97bee897fba2f44"
        }
      ]
    }
  ]
}
