{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform-utils/0.2.0/multiplatform-utils-0.2.0.module",
    "group": "com.github.juggernaut0",
    "module": "multiplatform-utils",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "emjam5nrhnavlmu2d4xtvs6aci"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.2.0.jar",
          "url": "multiplatform-utils-jvm-0.2.0.jar",
          "size": 20230,
          "sha512": "41929353eaa1334a5ffe0af0d1bafe876ac145a4cd44e41a389cb0db33b964b34114098a6ee4c5ebca498957fb0b6f652e551f85979b68e663fd9e0ba563f762",
          "sha256": "ed81defc821800f071b1e1d20bf98f586165c1aa3654b0fcc2640ddb2587a433",
          "sha1": "d9a5b66912bdfff164f4d108c349ee4623912b89",
          "md5": "8af6553ce1081fbd05ba7fdd8cc47a2b"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-utils-jvm-0.2.0.jar",
          "url": "multiplatform-utils-jvm-0.2.0.jar",
          "size": 20230,
          "sha512": "41929353eaa1334a5ffe0af0d1bafe876ac145a4cd44e41a389cb0db33b964b34114098a6ee4c5ebca498957fb0b6f652e551f85979b68e663fd9e0ba563f762",
          "sha256": "ed81defc821800f071b1e1d20bf98f586165c1aa3654b0fcc2640ddb2587a433",
          "sha1": "d9a5b66912bdfff164f4d108c349ee4623912b89",
          "md5": "8af6553ce1081fbd05ba7fdd8cc47a2b"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../multiplatform-utils-metadata/0.2.0/multiplatform-utils-metadata-0.2.0.module",
        "group": "com.github.juggernaut0",
        "module": "multiplatform-utils-metadata",
        "version": "0.2.0"
      }
    }
  ]
}
